- name: Prepare block disk(s) for virtual maschine(s)
  lvol:
    vg: "{{ item.value.disk[device].vg }}"
    lv: "{{ item.value.disk[device].lv }}"
    size: "{{ item.value.disk[device].size }}"
  with_dict: "{{ virt_guest_list }}"
  loop_control:
    label: "{{ item.value.disk[device] }}"
  when:
    # First condition doesn't work yet because Ansible have the bug: https://github.com/ansible/ansible/issues/27268
    # You will got the following error message with different numbers of disks: "dict object' has no attribute ..."
    # Therefore you must set the same numbers of disks for each virtual machine if you need more than one disk.
    - item.value.disk[device] is defined
    - item.value.disk[device].type | default('block') == "block"
    - item.value.disk[device].format | default('raw') == "raw"

- name: Prepare file disk(s) for virtual maschine(s)
  qemu_img:
    dest: "{{ virt_qemu_images_location }}/{{ item.value.disk[device].name }}.{{ item.value.disk[device].format }}"
    size: "{{ item.value.disk[device].size }}"
    format: "{{ item.value.disk[device].format | default('raw') }}"
    options: "{{ item.value.disk[device].format_options | default('preallocation=off') }}"
  with_dict: "{{ virt_guest_list }}"
  loop_control:
    label: "{{ item.value.disk[device] }}"
  when:
    # First condition doesn't work yet because Ansible have the bug: https://github.com/ansible/ansible/issues/27268
    # You will got the following error message with different numbers of disks: "dict object' has no attribute ..."
    # Therefore you must set the same numbers of disks for each virtual machine if you need more than one disk.
    - item.value.disk[device] is defined
    - item.value.disk[device].type | default('block') == "file"
    - item.value.disk[device].format | default('raw') in ["raw", "qcow2"]
