- name: Prepare block disk(s) for {{ vm_name }}
  lvol:
    vg: "{{ item.value.vg }}"
    lv: "{{ item.value.lv }}"
    size: "{{ item.value.size }}"
  loop: "{{ disk_list|dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when:
    - item.key is defined
    - item.value.device is not defined
    - item.value.type|default('block') == "block"
    - item.value.format|default('raw') == "raw"

- name: Prepare file disk(s) for {{ vm_name }}
  qemu_img:
    dest: "{{ virt_qemu_images_location }}/{{ item.value.name }}.{{ item.value.format }}"
    size: "{{ item.value.size }}"
    format: "{{ item.value.format|default('raw') }}"
    options: "{{ item.value.format_options|default('preallocation=off') }}"
  loop: "{{ disk_list|dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when:
    - item.key is defined
    - item.value.device is not defined
    - item.value.type|default('block') == "file"
    - item.value.format|default('raw') in ["raw", "qcow2"]
